# Generated by Django 2.1.2 on 2018-10-02 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('min_date', models.DateField()),
                ('max_date', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('data_coverage', models.FloatField()),
                ('elevation', models.FloatField()),
                ('elevation_unit', models.CharField(max_length=24)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
